### ISSUE TITLE
Decoding audio data causes EncodingErrorException

### ISSUE THREAD

**Issue by fyang93** [KristofferStrube/Blazor.MediaStreamRecording#1]
I was trying to decode each blob into raw audio byte array, but DecodeAudioDataAsync caused Kristofferstrube.Blazor.WeblDL.Exceptions.EncodingErrorException with message "Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data".
Here is my code, do you have any suggestions?

```C#
var recorderOptions = new MediaRecorderOptions
    {
        MimeType = "audio/webm; codecs=opus",
    };
audioRecorder = await MediaRecorder.CreateAsync(JS, audioStream, recorderOptions);

audioDataAvailableEventListener = await EventListener<BlobEvent>.CreateAsync(JS, async (BlobEvent e) =>
{
    var blob = await e.GetDataAsync();
    var audioData = await blob.ArrayBufferAsync();
    if (audioData.Length > 0)
    {
        var audioBuffer = await audioContext.DecodeAudioDataAsync(audioData);
        ...
    }
});
await audioRecorder.AddOnDataAvailableEventListenerAsync(audioDataAvailableEventListener);
```

**Comment by KristofferStrube** [comment]
Hey @fyang93 thanks for your interest in the library. 😁

The [DecodeAudioDataAsync](https://github.com/KristofferStrube/Blazor.WebAudio/blob/main/src/KristofferStrube.Blazor.WebAudio/BaseAudioContext.cs#L358) method throws an `EncodingErrorException` if <a href="https://mimesniff.spec.whatwg.org/#matching-an-audio-or-video-type-pattern">MIME Sniffing §6.2 Matching an audio or video type pattern</a> doesn't find a MIME type or if it failed to decode it into a linear PCM (pulse code modulation).

When OnDataAvailable is triggered each part isn't actually a valid audio bit alone as it is meant to be continued until the recording stops. So you need to connect all the parts of the recording before decoding for it to be successful. 

Could you elaborate on what your use case is? Then I might be able to make a demo that does just that or point you towards some other documentation. :)

**Comment by fyang93** [comment]
Sorry for being inactive for so long.
Instead of using recorder, I solved this issue by setting an AudioWorkletProcessor inside JS to capture the PCM data and sending it to C# via a workaround like `dotnet.invokeMethodAsync` stuff.
Anyway, it's appreciated that you made such a great library, it helped me a lot. Thanks :)

**Comment by KristofferStrube** [comment]
All good. :) I am working on something very similar for streaming sound from one browser to another as PCM data as well.
